version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-golang-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"